### ISSUE TITLE
What is the actual input voltage operating range for the buck-boost converter? 

### ISSUE THREAD

**Issue by DurvalMenezes** [Frapais/NanoCell-C3#1]
As per the subject. I can see it works at least in LiPo cell range (3.0 -4.2V), but can it be fed from eg NiMH  cells (1.2V nominal voltage)? What about a 12V LiFePO4 4S battery bank? 
This is of course dispensing with the charging functionality -- the LiFePO4 battery bank for example would be  kept charged by a solar panel setup.

Apologies in advance if that's somewhere in the docs/specs, but for the life of me I couldn't find it.

**Comment by Frapais** [comment]
The buck-boost converter operates in the range of 2.5V to 5.5V, so NiMH cells may not be suitable. Additionally, for batteries with more than one cell, an appropriate balancing circuit should be added, as the integrated circuit is for charging single-cell Lithium batteries only. However, if you experiment with this, please share your results.

**Comment by DurvalMenezes** [comment]
Thanks for the prompt and detailed response. Too bad the operating range is so restricted... it would be great if I could power it directly from the 12V bus I've already installed in my remote locations (fed from that battery bank which is then changed by solar panels).

**Comment by Frapais** [comment]
Actually, that seems very useful. I might consider this feature for the next version. Thanks for noticing!

**Comment by DurvalMenezes** [comment]
> Actually, that seems very useful. I might consider this feature for the next version. Thanks for noticing!

That would be perfect! 👍 if you can, please let me know by posting about it here in this issue, which I will be monitoring.

Thanks again!
